apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy-test-auth.yaml
  - service-test-auth.yaml

configMapGenerator:
  - name: auth-config
    literals:
      - ENV=default
      - DEBUG=false