apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy-test-hello.yaml
  - service-test-hello.yaml
  - ingress-test-hello.yaml

configMapGenerator:
  - name: helloworld-config
    literals:
      - ENV=default
      - DEBUG=false